# We should not hardcode the strings, we can maintain here, which will helpful for internationalization in future
JOB_LABEL="Job Title"
JOB_DESCRIPTION_LABEL="Job Descriptions"
JOB_TITLE_PLACEHOLDER = "Enter Job Title"
JOB_DESCRIPTION_PLACEHOLDER = "Enter Job Descriptions"
RESUME_LABEL="Upload Resume"
RESUME_UPLOAD_MESSAGE="Resume uploaded successfully!"
INTERVIEW_LABEL = "Interview Panel"
TRANSCRIPT_LABEL = "Transcription"
STOPWATCH_TIME = "Time"
ROBOT_IMAGE_PATH = "./src/resources/images/human-avatar.jpg"
INTERVIEW_ENDED = "✅ Interview Ended"
INTERVIEW_END_BUTTON = "End Interview"
GO_BACK = "Go Back"
